version: '3'
services:
#  db:
#    image: mongodb
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
#  backend:
#    build: ./backend
#    command: 
#    volumes:
#      - ./backend:/myapp/backend
#    ports:
#      - "3001:3000"
#    depends_on:
#      - db
  frontend:
    image: "node:10-alpine"
    user: "node"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    ports:
      - "3000:3000"
    command: "yarn start"
#    depends_on:
#      - backend
